import Foundation

/// Bundled English transliteration for every ayah (alquran.cloud
/// `en.transliteration`), loaded once. Kept parallel to `quran.json` — keyed by
/// surah number → ordered ayah strings (index = ayah − 1) — so we don't have to
/// regenerate the 2 MB main text file. Generated by `scripts/fetch_transliteration.py`.
struct QuranTransliteration: Sendable {
    static let shared = load()

    let bySurah: [Int: [String]]

    /// Whether the bundle is present (false only if the JSON wasn't fetched yet).
    var isAvailable: Bool { !bySurah.isEmpty }

    func text(surah: Int, ayah: Int) -> String? {
        guard let ayahs = bySurah[surah], ayah >= 1, ayah <= ayahs.count else { return nil }
        let value = ayahs[ayah - 1]
        return value.isEmpty ? nil : value
    }

    private struct File: Decodable {
        let surahs: [String: [String]]
    }

    private static func load() -> QuranTransliteration {
        guard let url = Bundle.main.url(forResource: "quran_transliteration", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let decoded = try? JSONDecoder().decode(File.self, from: data) else {
            return QuranTransliteration(bySurah: [:])
        }
        var map: [Int: [String]] = [:]
        map.reserveCapacity(decoded.surahs.count)
        for (key, value) in decoded.surahs {
            if let number = Int(key) { map[number] = value }
        }
        return QuranTransliteration(bySurah: map)
    }
}
